acmcsufoss/fullyhacks

.eslintrc.json, prisma/schema.prisma, src/components/LandingPage/CountDown/CountDown.tsx, src/components/LandingPage/FAQ/FAQ.tsx, src/components/NavBar/NavBar.tsx, src/pages/api/auth/[...nextauth].js
=> Landing Page works, still need to work on /apply, deployment test

src/components/LandingPage/About/About.tsx, src/components/LandingPage/Partners/Partners.tsx, src/components/LandingPage/Team/Team.tsx
While applying to FullyHacks, I noticed a few minor typos and grammatical errors on the `Landing Page`. My pull request fixes a few of these.
There are still some in the `FAQs`, which I can't fix without access to the API.
-vr
=> Fixed typos and grammar

src/components/LandingPage/About/About.tsx
I noticed there was no spacing in one of the index spans so I just added them.
=> Fix About section spacing

src/components/LandingPage/FAQ/FAQ.tsx
- added proper opne/close animations
- fixed hover effect
- fixed faq width to mathc widtgh of everything else
- disabled user select on question
- yes it is still mobile response
https://user-images.githubusercontent.com/8981287/227776805-9c79e8a8-fee9-4a17-a0d2-db29b400c500.mp4
=> fixed faq accordions

src/components/Calendar/Calendar.tsx, src/components/FeedPage/Events.tsx, src/styles/globals.css, src/types/interface.ts
=> Working on /feed events

src/components/Calendar/Calendar.tsx, src/components/FeedPage/FAQs.tsx, src/components/FeedPage/Feed.tsx, src/components/FeedPage/Prizes.tsx, src/components/LandingPage/FAQ/FAQ.tsx, src/components/NavBar/NavBar.tsx, src/pages/feed.tsx, src/types/interface.ts
=> Adding Prizes & Tracks

src/components/FeedPage/Prizes.tsx
* Capitalization adjustments
* Changing `front-tier` to `frontiers`
=> fix grammar and capitalization

src/components/FeedPage/FullyPacks.tsx, src/types/interface.ts
i have no idea how to test this without the database to log in to but i added a link to https://fullyhacks.notion.site/Free-Database-Providers-857f6fa883c5458f899f97a3f5e18f1c to backend development
=> add free databases to resources

src/components/LandingPage/FAQ/FAQ.tsx, tailwind.config.js
Implemented the FAQ section to match the Fullyhacks 2023 website redesign. Also made sure to handle responsiveness and add reusable colors inside tailwind.config. The only thing missing is the border upon expanding the question dropdown, but the implementation has a lot of breaking behaviors when interacting with the actual dropdown. I can try to make it work if it is totally necessary though. Please let me know if there are other things that I should reconsider as well. Thank you.
=> Landing page/faq

src/components/LandingPage/CountDown/CountDown.tsx, tailwind.config.js
=> countdown changed

src/components/LandingPage/CountDown/CountDown.tsx, src/components/NavBar/NavBar.tsx
=> fixed countdown whitespace + size, npm run format for navbar

src/components/Admin/Announcements/AnnouncementForm.tsx, src/components/FeedPage/Profile.tsx, src/styles/globals.css
Reimplemented the design of the Profile component in the Feed Page.
Looking like this:
Changed it for Admins as well:
=> Updated design of Profile tab (Feed Page)

package-lock.json, package.json, src/components/FeedPage/FullyPacks.tsx, src/components/FeedPage/Prizes.tsx, src/styles/globals.css, tailwind.config.js
Merge FullyPacks Changes into Main
=> FullyPacks Redesign

src/components/FeedPage/Resources.tsx
Changed it to match the Figma design.
The opacity alternates with even/odd number of elements.
=> Updated Resources (Feed Page)

src/components/Calendar/Calendar.tsx, src/components/FeedPage/Announcements.tsx, src/components/FeedPage/Events.tsx, src/components/FeedPage/FAQs.tsx, src/components/FeedPage/FullyPacks.tsx, src/components/FeedPage/Prizes.tsx, src/components/FeedPage/Profile.tsx, src/components/FeedPage/Resources.tsx, src/components/LandingPage/FAQ/FAQ.tsx, src/components/NavBar/NavBar.tsx
Did a couple things to enhance UX in Feed Page:
- Updated FAQ component to adapt font size in smaller screen sizes.
- Removed margin from left side of Feed Page.
- Fixed unresponsive Track & Prizes component.
- Added "all" filter in Events (Feed Page)
- Reimplemented Navbar to not occupy space (slidable side bar).
Here's how the new navbar looks like:
https://github.com/acmcsufoss/fullyhacks/assets/112128328/52658d76-6fd1-41de-a1e5-c2bd5a39f5e6
=> Fixed Responsiveness of Feed Page + some more things

src/components/nav-bar.tsx
Added a simple rewrite to a couple of the navbar components to use Next's Link component rather than pushing with the router. This keeps it consistent.
=> Rewrite small routing logic for navbars

src/app/(site)/_components/count-down.tsx, src/app/(site)/_components/hero.tsx, src/app/(site)/_components/landing-page.tsx
Added Hero Section
Updated countdown styles, button styles, and improved mobile styles of Hero
Fixes #79
=> Added Hero Section

src/app/(site)/feed/_components/faq.tsx, src/components/footer.tsx, src/components/nav-bar.tsx, src/lib/data/links.json
Added important urls such as social media links and a discord server invites in a json to act as a single source of truth
=> Add important urls in json

src/app/(site)/feed/home/_components/feed-users.tsx, src/app/(site)/feed/home/page.tsx, src/app/(site)/feed/profile/page.tsx, src/styles/globals.css, tailwind.config.js
Page where you will be able to see all hackathon participants and organizers!
=> FH 2025 Home

package-lock.json, package.json
[Next.js already has built-in support for cookies.](https://nextjs.org/docs/app/api-reference/functions/cookies) Its usage is in [the middleware for profile updates.](https://github.com/acmcsufoss/fullyhacks/blob/main/src/middleware/profileUpdateMiddleware.ts)
=> Remove "cookie" and "@types/cookie" packages

public/assets/among-us.svg, src/app/(site)/error.tsx, src/app/not-found.tsx, src/components/nav-bar.tsx, src/styles/globals.css
Resolves #111.
With this change I also added some small changes:
- Animation on the portal background image, smoothly rotating around x or y if there is space available!
- Underline hover effect on the Sign Out button, same as the navbar items
=> Implement 2025 error and 404 pages

src/app/(site)/apply/_components/application-form.tsx, src/app/(site)/apply/_components/school-suggestion.tsx
An error about an "invalid school" occurs when clicking on submit the first time. When clicking submit again, it goes away since the user's school is properly submitted. This happens since the school value being validated in the `search` state under `school-suggestion.tsx` is the value the user typed in (i.e `fullerton`) rather than the school they clicked (`California State University-Fullerton`) in `usuni.json`. I added a setValue to ensure that the school they clicked on is reflected in the application.
=> fix: invalid school error when first clicking submit in application form

src/app/(site)/apply/_components/application-form.tsx, src/app/(site)/apply/_components/apply-auth.tsx, src/app/(site)/apply/_components/school-suggestion.tsx, src/app/(site)/apply/page.tsx, src/styles/globals.css, tailwind.config.js
=> FullyHacks 2025 Application Page

src/schemas/application.ts
Update the minimum grad year to apply to 2025
=> update min grad year to 2025

src/app/(site)/admin/_components/application.tsx, src/app/(site)/admin/_components/applications.tsx, src/app/(site)/feed/faq/_components/faq.tsx
=> added pagination for viewing apps

prisma/schema.prisma, src/app/(site)/admin/_components/admin-view.tsx, src/app/(site)/admin/_components/application.tsx, src/app/(site)/admin/_components/applications.tsx, src/app/(site)/admin/page.tsx, src/app/(site)/feed/layout.tsx, src/app/(site)/feed/profile/page.tsx, src/app/(site)/portal/_components/user-portal.tsx, src/app/api/application/[id]/route.ts, src/components/loading.tsx, src/types/interface.ts
Key features:
- Change the color scheme of the admin page to match closer to the overall FH website color scheme
- Work on adding a `waitlist` option to more easily waitlist applicants
=> FullyHacks 2025 Admin
